
services:
  # ======================
  # HEALENIUM SERVICE
  # ======================
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=healenium_pass
    volumes:
      - ./init-healenium-db.sql:/docker-entrypoint-initdb.d/init-healenium-db.sql
    networks:
      - healenium
  healenium-backend:
    image: healenium/hlm-backend:3.3.0
    container_name: healenium-backend
    restart: always
    ports:
      - "7878:7878"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/healenium?currentSchema=healenium
      - SPRING_DATASOURCE_USERNAME=healenium_user
      - SPRING_DATASOURCE_PASSWORD=healenium_pass
    depends_on:
      - postgres-db
    networks:
      - healenium


  selector-imitator:
    image: healenium/hlm-selector-imitator:1.2
    container_name: selector-imitator
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://healenium-backend:7878
    depends_on:
      - healenium-backend
    networks:
      - healenium

    # ======================
    # SELENIUM GRID
    # ======================
  selenium-hub:
    image: selenium/hub:4.20.0
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
  node-chrome:
    image: selenium/node-chrome:4.20.0
    container_name: node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid
  node-firefox:
    image: selenium/node-firefox:4.20.0
    container_name: node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid
  node-edge:
    image: selenium/node-edge:4.20.0
    container_name: node-edge
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

networks:
  healenium:
    driver: bridge
  grid:
    driver: bridge