services:
  # ======================
  # HEALENIUM SERVICE
  # ======================
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=healenium_pass
    volumes:
      - ./init-healenium-db.sql:/docker-entrypoint-initdb.d/init-healenium-db.sql
    networks:
      - healenium
  healenium-backend:
    image: healenium/hlm-backend:3.3.0
    container_name: healenium-backend
    restart: always
    ports:
      - "7878:7878"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/healenium?currentSchema=healenium
      - SPRING_DATASOURCE_USERNAME=healenium_user
      - SPRING_DATASOURCE_PASSWORD=healenium_pass
    depends_on:
      - postgres-db
    networks:
      - healenium


  selector-imitator:
    image: healenium/hlm-selector-imitator:1.2
    container_name: selector-imitator
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://healenium-backend:7878
    depends_on:
      - healenium-backend
    networks:
      - healenium

networks:
  healenium:
    driver: bridge