<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.automation</groupId>
  <artifactId>opencart-automation-framework</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>opencart-automation-framework</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <build>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-surefire-plugin</artifactId>
              <version>3.5.5</version>
              <configuration>
                  <suiteXmlFiles>
<!--                      <suiteXmlFile>testng-all.xml</suiteXmlFile>-->
                      <!--suppress UnresolvedMavenProperty -->
                      <suiteXmlFile>${suiteFile}</suiteXmlFile>
                  </suiteXmlFiles>
                  <properties>
                      <property>
                          <name>usedefaultlisteners</name>
                          <value>false</value>
                      </property>
                  </properties>
                  <argLine>-Dfile.encoding=UTF-8</argLine>
              </configuration>
              <dependencies>
                  <dependency>
                      <groupId>org.apache.maven.surefire</groupId>
                      <artifactId>surefire-testng</artifactId>
                      <version>3.5.5</version>
                  </dependency>
              </dependencies>
          </plugin>
      </plugins>
  </build>
  <dependencies>
      <!-- Selenium WebDriver -->
      <!-- Source: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
      <dependency>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-java</artifactId>
          <version>4.39.0</version>
      </dependency>
      <!-- TestNG -->
      <!-- Source: https://mvnrepository.com/artifact/org.testng/testng -->
      <dependency>
          <groupId>org.testng</groupId>
          <artifactId>testng</artifactId>
          <version>7.10.2</version>
          <scope>test</scope>
      </dependency>
      <!-- Apache POI cho Data Driven Testing -->
      <!-- Source: https://mvnrepository.com/artifact/org.apache.poi/poi -->
      <dependency>
          <groupId>org.apache.poi</groupId>
          <artifactId>poi</artifactId>
          <version>5.5.1</version>
          <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
      <dependency>
          <groupId>org.apache.poi</groupId>
          <artifactId>poi-ooxml</artifactId>
          <version>5.5.1</version>
          <scope>compile</scope>
      </dependency>
      <!-- Extent Reports cho báo cáo -->
      <!-- Source: https://mvnrepository.com/artifact/com.aventstack/extentreports -->
      <dependency>
          <groupId>com.aventstack</groupId>
          <artifactId>extentreports</artifactId>
          <version>5.1.1</version>
          <scope>compile</scope>
      </dependency>
      <!-- Log4j cho Logging -->
      <!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core -->
      <dependency>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-core</artifactId>
          <version>2.25.3</version>
          <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api -->
      <dependency>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-api</artifactId>
          <version>2.25.3</version>
          <scope>compile</scope>
      </dependency>
<!--      WebDriverManager (auto driver)-->
      <!-- Source: https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager -->
      <dependency>
          <groupId>io.github.bonigarcia</groupId>
          <artifactId>webdrivermanager</artifactId>
          <version>6.3.3</version>
          <scope>compile</scope>
      </dependency>

<!--      Fake data-->
      <!-- Source: https://mvnrepository.com/artifact/com.github.javafaker/javafaker -->
      <dependency>
          <groupId>com.github.javafaker</groupId>
          <artifactId>javafaker</artifactId>
          <version>1.0.2</version>
          <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/com.epam.healenium/healenium-web -->
      <dependency>
          <groupId>com.epam.healenium</groupId>
          <artifactId>healenium-web</artifactId>
          <version>3.6.0</version>
          <scope>compile</scope>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/com.google.inject/guice -->
      <dependency>
          <groupId>com.google.inject</groupId>
          <artifactId>guice</artifactId>
          <version>7.0.0</version>
          <scope>compile</scope>
      </dependency>

  </dependencies>
</project>
